# Image URL to use all building/pushing image targets
IMAGE_REGISTRY = quay.io
REGISTRY_NAMESPACE = origin-odf
IMAGE_TAG = v4.15.0
IMAGE_NAME = odf-operator
BUNDLE_IMAGE_NAME = $(IMAGE_NAME)-bundle
CATALOG_IMAGE_NAME = $(IMAGE_NAME)-catalog

OCS_BUNDLE_NAME ?= ocs-operator
OCS_BUNDLE_IMG_NAME ?= $(OCS_BUNDLE_NAME)-bundle
OCS_BUNDLE_IMG_TAG = v4.15.0
OCS_BUNDLE_IMG_LOCATION ?= quay.io/ocs-dev
OCS_BUNDLE_IMG ?= $(OCS_BUNDLE_IMG_LOCATION)/$(OCS_BUNDLE_IMG_NAME):$(OCS_BUNDLE_IMG_TAG)

NOOBAA_BUNDLE_NAME ?= noobaa-operator
NOOBAA_BUNDLE_IMG_NAME ?= $(NOOBAA_BUNDLE_NAME)-bundle
NOOBAA_BUNDLE_IMG_TAG ?= v5.14.0
NOOBAA_BUNDLE_IMG_LOCATION ?= quay.io/noobaa
NOOBAA_BUNDLE_IMG ?= $(NOOBAA_BUNDLE_IMG_LOCATION)/$(NOOBAA_BUNDLE_IMG_NAME):$(NOOBAA_BUNDLE_IMG_TAG)

CSIADDONS_BUNDLE_NAME ?= csi-addons
CSIADDONS_BUNDLE_IMG_NAME ?= k8s-bundle
CSIADDONS_BUNDLE_IMG_TAG ?= v0.7.0
CSIADDONS_BUNDLE_IMG_LOCATION ?= quay.io/csiaddons
CSIADDONS_BUNDLE_IMG ?= $(CSIADDONS_BUNDLE_IMG_LOCATION)/$(CSIADDONS_BUNDLE_IMG_NAME):$(CSIADDONS_BUNDLE_IMG_TAG)

IBM_BUNDLE_NAME ?= ibm-storage-odf-operator
IBM_BUNDLE_IMG_NAME ?= $(IBM_BUNDLE_NAME)-bundle
IBM_BUNDLE_IMG_TAG ?= 1.4.1
IBM_BUNDLE_IMG_LOCATION ?= quay.io/ibmodffs
IBM_BUNDLE_IMG ?= $(IBM_BUNDLE_IMG_LOCATION)/$(IBM_BUNDLE_IMG_NAME):$(IBM_BUNDLE_IMG_TAG)

ODF_CONSOLE_IMG_NAME ?= odf-console
ODF_CONSOLE_IMG_TAG ?= latest
ODF_CONSOLE_IMG_LOCATION ?= quay.io/ocs-dev
ODF_CONSOLE_IMG ?= $(ODF_CONSOLE_IMG_LOCATION)/$(ODF_CONSOLE_IMG_NAME):$(ODF_CONSOLE_IMG_TAG)

# kube rbac proxy image variable
OSE_KUBE_RBAC_PROXY_IMG = quay.io/openshift/origin-kube-rbac-proxy:4.14